version: "3.9"

services:
  api:
    container_name: project_fullstack
    build: .
    ports:
      - 3333:3333
    environment:
      - DB_HOST=db
      - DB_PASSWORD=sunnylee
      - DB=projectfullstack
      - DB_USER=talitta
    depends_on:
      - db
  db:
    container_name: db_fullstack
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=talitta
      - POSTGRES_PASSWORD=sunnylee
      - POSTGRES_DB=projectfullstack
    volumes:
      - postgres_demo:/var/lib/postgresql/data
volumes:
  postgres_demo:
    driver: local
